FROM atlassian/jira-software:9.12.6
RUN apt-get update && \
    apt-get install -y libappindicator1 fonts-liberation && \
    apt-get install -f && \
    curl https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o chrome.deb && \
    apt install ./chrome.deb  --fix-broken -y && \
    rm -f chrome.dev && \
    apt-get clean && \
    apt-get autoclean
